# /etc/bash/bashrc
#
# This file is sourced by all *interactive* bash shells on startup,
# including some apparently interactive shells such as scp and rcp
# that can't tolerate any output.  So make sure this doesn't display
# anything or bad things will happen !

# Test for an interactive shell.  There is no need to set anything
# past this point for scp and rcp, and it's important to refrain from
# outputting anything in those cases.
if [[ $- != *i* ]]; then
	# Shell is non-interactive.  Be done now!
	return
fi

# Bash won't get SIGWINCH if another process is in the foreground.
# Enable checkwinsize so that bash will check the terminal size when
# it regains control.  #65623
# http://cnswww.cns.cwru.edu/~chet/bash/FAQ (E11)
shopt -s checkwinsize

# Disable completion when the input buffer is empty.  i.e. Hitting tab
# and waiting a long time for bash to expand all of $PATH.
# shopt -s no_empty_cmd_completion

# Enable history appending instead of overwriting when exiting.  #139609
shopt -s histappend

# Env Vars
export PATH="$HOME/.local/bin:$PATH"
export PATH="$HOME/.emacs.d/bin:$PATH"

export GITUSER="$(git config -f $HOME/.config/git/config --get user.name)"
export DOTFILES="$HOME/repos/github.com/$GITUSER/nixos-config"
export GHREPOS="$HOME/repos/github.com/$GITUSER/"

alias grep='grep --colour=auto'
alias egrep='egrep --colour=auto'
alias fgrep='fgrep --colour=auto'
alias du='du -h -a --total'
alias la='ls -al'
alias free='free -h'
alias dots='cd ${DOTFILES}'
alias nb='nix build'
alias v='nvim'
alias vim='nvim'
alias vi='nvim'
alias gs='git status'
alias ga='git add'
alias gc='git commit'
alias gp='git push'

p() {
  cd $(find $GHREPOS -maxdepth 1 ! -path $GHREPOS -type d | fzf)
}

# Prompt
PROMPT_LONG=70
PROMPT_MAX=95

__ps1() {
  PS1="┌─[\[\e[01;35m\]\u\[\e[00m\]@\[\e[01;35m\]\h\[\e[00m\]:\[\e[1;34m\]\w\[\e[0m\]]\n└─╼ "
}

PROMPT_COMMAND="__ps1"
