(use-package modalka
  :config
  (modalka-define-kbd "W" "M-w")
  (modalka-define-kbd "Y" "M-y")
  (modalka-define-kbd "a" "C-a")
  (modalka-define-kbd "b" "M-b")
  (modalka-define-kbd "e" "C-e")
  (modalka-define-kbd "f" "M-f")
  (modalka-define-kbd "g" "C-g")
  (modalka-define-kbd "n" "C-n")
  (modalka-define-kbd "p" "C-p")
  (modalka-define-kbd "y" "C-y")
  (modalka-define-kbd "d" "M-d")
  (modalka-define-kbd "m" "M->")
  (modalka-define-kbd "M" "M-<")
  (modalka-define-kbd "s" "C-x C-s")
  (modalka-define-kbd "SPC" "C-SPC")
  (modalka-define-kbd "o" "C-x o")
  (modalka-define-kbd "1" "C-x 1")
  (modalka-define-kbd "2" "C-x 2")
  (modalka-define-kbd "3" "C-x 3")
  (global-set-key (kbd "<escape>") #'modalka-mode))
